Backend and Frontend connected, #24
vystartasv/kodflix pull request #8
Opened 2019-04-12 09:10 UTC by vystartasv

Please review my code, many thanks

2019-04-12 10:28 UTC, rmallols requested changes

2019-04-12 10:28 UTC, rmallols commented on package.json
> +    "build": "NODE_ENV=prod react-scripts build",
Do you need `NODE_ENV=prod` here? I believe it shouldn't be necessary

2019-04-12 10:28 UTC, rmallols commented on src/backend/server.js
> +app.get(['/api/shows', '/api/shows/:showId'], (req, res) => {
You can simplify this by simply putting `/api/shows/:showId*?`

2019-04-12 10:28 UTC, rmallols commented on src/frontend/components/Details.js
> +
Unnecessary empty line here

2019-04-12 10:28 UTC, rmallols commented on src/frontend/components/Details.js
> +    componentWillMount() {
Mmmm I think this can be massively simplified!!!

You should **never** refer to the absolute path on the . frontend, as all the URLs should be relative.

In other words, simply do `fetch('/api/shows/${name}`') and it should work on any environment :))

2019-04-12 10:28 UTC, rmallols commented on src/frontend/components/Gallery.js
>  // import { strictEqual } from "assert";
Unnecessary comment

2019-04-12 10:28 UTC, rmallols commented on src/frontend/components/Gallery.js
> +    componentWillMount() {
Same as above

2019-04-12 11:04 UTC, vystartasv commented on package.json
> +    "build": "NODE_ENV=prod react-scripts build",
Will leave only def environment, need to update more classes

2019-04-12 11:07 UTC, vystartasv commented on src/backend/server.js
> +app.get(['/api/shows', '/api/shows/:showId'], (req, res) => {
Trying to follow best practices for rest api https://restfulapi.net/resource-naming/

2019-04-12 11:13 UTC, vystartasv commented on src/frontend/components/Details.js
> +    componentWillMount() {
Amend in the next one commit

2019-04-23 13:22 UTC, vystartasv commented on package.json
> +    "build": "NODE_ENV=prod react-scripts build",
updated in further commits

2019-04-23 13:22 UTC, vystartasv commented on src/frontend/components/Details.js
> +
removed

2019-04-23 13:22 UTC, vystartasv commented on src/frontend/components/Gallery.js
>  // import { strictEqual } from "assert";
removed import

2019-04-23 13:24 UTC, vystartasv commented on src/frontend/components/Details.js
> +    componentWillMount() {
all the paths updated with relative values

2019-04-23 13:24 UTC, merged