Added global Menu element, task #33
vystartasv/kodflix pull request #9
Opened 2019-04-23 20:32 UTC by vystartasv

2019-04-23 20:33 UTC, vystartasv commented
Many thanks for checking, hope I am not inventing the wheel.

2019-04-24 16:00 UTC, rmallols requested changes

2019-04-24 16:00 UTC, rmallols commented on src/frontend/App.js
>  class App extends Component {
Mmmm...any reason why  you changed indentation?

2019-04-24 16:00 UTC, rmallols commented on src/frontend/components/Menu.css
> +    z-index: 1000;
I wouldn't put  `100` here, feels a bit random. Why don't you set it to something like `1` or `2`?

2019-04-24 16:52 UTC, vystartasv commented on src/frontend/App.js
>  class App extends Component {
Configured project with eslint and applied Airbnb rules, it complained a lot more, like rect components not having jsx extensions, not using restructuring assignments, etc.

2019-04-24 16:54 UTC, vystartasv commented on src/frontend/components/Menu.css
> +    z-index: 1000;
Played around, forgot to undo, actually meant to have different value

2019-04-25 09:48 UTC, rmallols requested changes

2019-04-25 09:48 UTC, rmallols commented on src/frontend/components/Menu.css
> +    z-index: 50;
Still, why 50 instead of  `1`?

2019-04-26 11:04 UTC, rmallols approved these changes
Fantastic, thanks mate :)

2019-04-30 10:32 UTC, rmallols approved these changes
Cool, I really like the  way you structured routing, well done Vilius :)

2019-05-16 16:29 UTC, merged